apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: NodePort
  selector:
    app: db
  ports:
    - name: db
      protocol: TCP
      nodePort: 30010
      port: 5432
      targetPort: 5432