apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-deployment
  labels:
    service: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      name: crud
      labels:
        app: crud
    spec:
      containers:
      - name: st1607-crud
        image: juansedo/st1607-crud:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: crud-secret-credentials