apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  type: NodePort
  selector:
    app: crud
  ports:
    - name: crud
      protocol: TCP
      nodePort: 30001
      port: 3000
      targetPort: 3000