apiVersion: v1
kind: Service
metadata:
  name: map-service
spec:
  type: NodePort
  selector:
    app: map
  ports:
    - name: map
      protocol: TCP
      nodePort: 30002
      port: 3000
      targetPort: 3000