apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: st1607-front
        image: juansedo/st1607-front:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80